In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [85]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingClassifier

In [86]:
cars = pd.read_csv("cars_raw.csv")

In [87]:
cars.head()

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage
0,2019,Toyota,Sienna SE,Used,"$39,998",4.6,45,Dealer,CarMax Murrieta - Now offering Curbside Pickup...,3.3,...,Black,Front-wheel Drive,19,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,5TDXZ3DC2KS015402,22998646,29403
1,2018,Ford,F-150 Lariat,Used,"$49,985",4.8,817,Dealer,Giant Chevrolet,4.8,...,Black,Four-wheel Drive,19,24,Gasoline,10-Speed Automatic,3.5L V6 24V PDI DOHC Twin Turbo,1FTEW1EG2JFD44217,22418A,32929
2,2017,RAM,1500 Laramie,Used,"$41,860",4.7,495,Dealer,Gill Auto Group Madera,4.6,...,Black,Four-wheel Drive,15,21,Gasoline,8-Speed Automatic,5.7L V8 16V MPFI OHV,1C6RR7VT5HS842283,NG277871G,23173
3,2021,Honda,Accord Sport SE,Used,"$28,500",5.0,36,Dealer,AutoSavvy Las Vegas,4.6,...,–,Front-wheel Drive,29,35,Gasoline,Automatic CVT,1.5L I4 16V GDI DOHC Turbo,1HGCV1F49MA038035,54237,10598
4,2020,Lexus,RX 350,Used,"$49,000",4.8,76,Dealer,Lexus of Henderson,4.8,...,Birch,Front-wheel Drive,20,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,2T2AZMAA8LC156270,HDT4181A,28137

In [88]:
cars.shape

(9379, 32)

In [89]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 9379 entries, 0 to 9378
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   9379 non-null   int64
 1   Make                   9379 non-null   str
 2   Model                  9379 non-null   str
 3   Used/New               9379 non-null   str
 4   Price                  9379 non-null   str
 5   ConsumerRating         9379 non-null   float64
 6   ConsumerReviews        9379 non-null   int64
 7   SellerType             9379 non-null   str
 8   SellerName             9379 non-null   str
 9   SellerRating           9379 non-null   float64
 10  SellerReviews          9379 non-null   int64
 11  StreetName             9379 non-null   str
 12  State                  9379 non-null   str
 13  Zipcode                9379 non-null   str
 14  DealType               9157 non-null   str
 15  ComfortRating          9379 non-null   float64
 16  InteriorDesignRating   9379 non-null   float64
 17  PerformanceRating      9379 non-null   float64
 18  ValueForMoneyRating    9379 non-null   float64
 19  ExteriorStylingRating  9379 non-null   float64
 20  ReliabilityRating      9379 non-null   float64
 21  ExteriorColor          9379 non-null   str
 22  InteriorColor          9379 non-null   str
 23  Drivetrain             9379 non-null   str
 24  MinMPG                 9379 non-null   int64
 25  MaxMPG                 9379 non-null   int64
 26  FuelType               9379 non-null   str
 27  Transmission           9379 non-null   str
 28  Engine                 9379 non-null   str
 29  VIN                    9379 non-null   str
 30  Stock#                 9379 non-null   str
 31  Mileage                9379 non-null   int64
dtypes: float64(8), int64(6), str(18)
memory usage: 2.3 MB

In [90]:
cars.describe()

,Year,ConsumerRating,ConsumerReviews,SellerRating,SellerReviews,ComfortRating,InteriorDesignRating,PerformanceRating,ValueForMoneyRating,ExteriorStylingRating,ReliabilityRating,MinMPG,MaxMPG,Mileage
count,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000,9379.000000
mean,2018.721719,4.702825,133.187014,4.412571,984.089988,4.771895,4.727391,4.696290,4.537083,4.782194,4.681746,22.755411,29.216548,37463.023350
std,2.221708,0.240795,154.985640,0.626258,1609.039864,0.217822,0.194391,0.253664,0.338098,0.171537,0.368161,14.812869,12.809783,24970.342569
min,2001.000000,2.500000,1.000000,1.000000,1.000000,3.000000,2.800000,1.000000,1.000000,3.000000,1.000000,0.000000,0.000000,121.000000
25%,2018.000000,4.700000,30.000000,4.300000,112.000000,4.700000,4.700000,4.600000,4.500000,4.700000,4.600000,18.000000,25.000000,18666.500000
50%,2019.000000,4.800000,75.000000,4.600000,542.000000,4.800000,4.800000,4.700000,4.600000,4.800000,4.800000,20.000000,27.000000,32907.000000
75%,2020.000000,4.800000,182.000000,4.800000,1272.000000,4.900000,4.800000,4.800000,4.700000,4.900000,4.900000,24.000000,31.000000,47698.000000
max,2022.000000,5.000000,817.000000,5.000000,27824.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,150.000000,133.000000,234114.000000

In [91]:
cars[cars['Used/New'] != 'Used'].head()

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage
9,2020,Dodge,Charger Scat Pack,Dodge Certified,"$46,773",4.8,56,Dealer,Bill Luke Chrysler Jeep Dodge RAM,4.3,...,Black,Rear-wheel Drive,15,24,Gasoline,8-Speed Automatic,6.4L V8 16V MPFI OHV,2C3CDXGJ8LH157532,CBY705,25642
13,2020,Dodge,Charger Scat Pack,Dodge Certified,"$47,500",4.8,56,Dealer,Tempe Dodge Chrysler Jeep RAM,4.7,...,Black,Rear-wheel Drive,15,24,Gasoline,8-Speed Automatic,6.4L V8 16V MPFI OHV,2C3CDXGJ5LH162364,NK11114B,31538
40,2022,Acura,MDX A-Spec,Acura Certified,"$58,995",4.9,16,Dealer,Frank Leta Acura,4.6,...,Ebony,All-wheel Drive,19,25,Gasoline,10-Speed Automatic,3.5L V6 24V GDI SOHC,5J8YE1H06NL004768,PA2258,12531
46,2021,Honda,Pilot Special Edition,Honda Certified,"$43,296",4.8,63,Dealer,Ed Martin Honda,4.8,...,Gray,All-wheel Drive,19,26,Gasoline,Automatic,Regular Unleaded V-6 3.5 L/212,5FNYF6H29MB101863,2CR3252A,10563
76,2019,Mercedes-Benz,AMG E 63 S 4MATIC,Mercedes-Benz Certified,"$106,999",5.0,2,Dealer,Ray Catena Mercedes Benz Freehold,4.7,...,Brown,All-wheel Drive,15,23,Gasoline,9-Speed Automatic,4.0L V8 32V GDI DOHC Twin Turbo,WDDZF8KB9KA505055,P3020,15113

In [92]:
cars[['Make','Model','Price','ConsumerRating','ConsumerReviews','SellerType','SellerRating','InteriorColor','Drivetrain','MinMPG','MaxMPG','FuelType', 'Transmission','Engine','Mileage']].head()

,Make,Model,Price,ConsumerRating,ConsumerReviews,SellerType,SellerRating,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,Mileage
0,Toyota,Sienna SE,"$39,998",4.6,45,Dealer,3.3,Black,Front-wheel Drive,19,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,29403
1,Ford,F-150 Lariat,"$49,985",4.8,817,Dealer,4.8,Black,Four-wheel Drive,19,24,Gasoline,10-Speed Automatic,3.5L V6 24V PDI DOHC Twin Turbo,32929
2,RAM,1500 Laramie,"$41,860",4.7,495,Dealer,4.6,Black,Four-wheel Drive,15,21,Gasoline,8-Speed Automatic,5.7L V8 16V MPFI OHV,23173
3,Honda,Accord Sport SE,"$28,500",5.0,36,Dealer,4.6,–,Front-wheel Drive,29,35,Gasoline,Automatic CVT,1.5L I4 16V GDI DOHC Turbo,10598
4,Lexus,RX 350,"$49,000",4.8,76,Dealer,4.8,Birch,Front-wheel Drive,20,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,28137

In [93]:
cars[cars['SellerType'] != 'Dealer'].head()

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage
31,2016,Honda,Odyssey EX-L,Used,"$28,999",4.7,100,Private,Darshan,4.7,...,Beige,Front-wheel Drive,19,28,Gasoline Fuel,6-Speed A/T,248.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,5FNRL5H66GB090450,–,56000
39,2017,Land,Rover Range Rover Evoque SE Premium,Used,"$34,555",4.3,42,Private,Jason,4.7,...,Beige,Four-wheel Drive,21,29,Gasoline Fuel,Transmission w/Dual Shift Mode,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,SALVP2BG1HH214962,–,39855
43,2013,INFINITI,G37 x,Used,"$17,300",4.7,131,Private,stan,4.7,...,Black,All-wheel Drive,18,25,Gasoline Fuel,7-Speed A/T,328.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,JN1CV6AR5DM756312,–,66560
45,2017,Tesla,Model S 75,Used,"$47,000",4.6,37,Private,Kenny,4.2,...,White,Rear-wheel Drive,0,0,Electric Fuel System,A/T,382.0HP Electric Motor Electric Fuel System,5YJSA1E17HF196111,–,84000
56,2017,Land,Rover Range Rover Sport 3.0L Supercharged HSE ...,Used,"$53,000",4.8,38,Private,Owais,3.6,...,Red,Four-wheel Drive,17,23,Gasoline Fuel,8-Speed A/T,380.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,SALWV2FV0HA134046,–,55000

In [94]:
dummies_make = pd.get_dummies(cars['Make'], prefix='make', dtype=int)
dummies_make.head()

,make_Acura,make_Alfa,make_Audi,make_BMW,make_Bentley,make_Buick,make_Cadillac,make_Chevrolet,make_Chrysler,make_Dodge,...,make_Nissan,make_Porsche,make_RAM,make_Saturn,make_Scion,make_Subaru,make_Tesla,make_Toyota,make_Volkswagen,make_Volvo
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
data =cars[['Used/New','Price','ConsumerRating','ConsumerReviews','SellerType','SellerRating','InteriorColor','Drivetrain','MinMPG','MaxMPG','FuelType','Transmission','Engine','Mileage']]

data.loc[data['Price'].str.contains('Not Priced', case=False, na=False),'Price'] = '0'

data['Price'] = data['Price'].str.replace('$', '',regex=False).str.replace(',', '', regex=False).astype(int)

In [96]:
data['Used/New'] = data['Used/New'].str.replace('Used', '0', regex=False)
data.loc[data['Used/New'].str.contains('certified', case=False, na=False), 'Used/New'] = '1'
data['Used/New'] = data['Used/New'].astype(int)

In [97]:
X = data.drop(columns=['Used/New'])
Y = pd.Series(data['Used/New'], name='target')

In [98]:
columnas_numericas = ['Price', 'ConsumerRating', 'ConsumerReviews', 'SellerRating', 'MinMPG', 'MaxMPG', 'Mileage']
columnas_categoricas = ['FuelType', 'Transmission', 'Drivetrain', 'SellerType']
X_num = data[columnas_numericas]
X_cat = pd.get_dummies(data[columnas_categoricas], dtype=int)
Xdum = pd.concat([X_num, X_cat], axis=1)

In [106]:
Xdum.head()

,Price,ConsumerRating,ConsumerReviews,SellerRating,MinMPG,MaxMPG,Mileage,FuelType_Diesel,FuelType_Diesel Fuel,FuelType_E85 Flex Fuel,...,Drivetrain_All-wheel Drive,Drivetrain_FWD,Drivetrain_Four-wheel Drive,Drivetrain_Front Wheel Drive,Drivetrain_Front-wheel Drive,Drivetrain_RWD,Drivetrain_Rear-wheel Drive,Drivetrain_–,SellerType_Dealer,SellerType_Private
0,39998,4.6,45,3.3,19,27,29403,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,49985,4.8,817,4.8,19,24,32929,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,41860,4.7,495,4.6,15,21,23173,0,0,0,...,0,0,1,0,0,0,0,0,1,0
3,28500,5.0,36,4.6,29,35,10598,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,49000,4.8,76,4.8,20,27,28137,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [99]:
X_train, X_test, y_train, y_test = train_test_split(Xdum, Y, test_size=0.2, random_state=42)

In [100]:

scaler = StandardScaler()

In [101]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [107]:
model = LogisticRegression(C=0.1, max_iter=1000, solver='lbfgs')

In [108]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

In [109]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.84

In [110]:
model_gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
scores = cross_val_score(model_gb, Xdum, Y, cv=5)
print(f"Accuracy promedio: {scores.mean():.2f}")

Accuracy promedio: 0.84